version: '2'
services:
  db:
    image: mariadb:10.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  candlepin:
    image: ${REGISTRY}/candlepin-base
    environment:
      USING_MYSQL: "true"
      DBHOSTNAME: db
    privileged: true
    volumes:
      - ../:/candlepin-dev
    depends_on:
      - db
